# Generated by Django 2.0.13 on 2019-08-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190817_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.FloatField(),
        ),
    ]
