"""empty message

Revision ID: 60486c13ab73
Revises: d866d88421aa
Create Date: 2019-08-07 01:13:11.847373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60486c13ab73'
down_revision = 'd866d88421aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vocabularies', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vocabularies', 'count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
