"""empty message

Revision ID: 8f4435d0f844
Revises: c5680d6c0e45
Create Date: 2019-08-06 23:45:24.767305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4435d0f844'
down_revision = 'c5680d6c0e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('added_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'added_on')
    # ### end Alembic commands ###
